apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cross-namespace
  namespace: tenant-a
spec:
  endpointSelector: {}    
    ingress:
      - fromEndpoints:
          - {}
      - fromEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: tenant-b
    egress:
      - toEndpoints:
          - {}
      - toEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: 53
                protocol: ANY
            rules:
              dns:
                - matchPattern: "*"
