apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cross-namespace
  namespace: tenant-a
specs:
  - endpointSelector: {}
    description: "For all pods in tenant-a namespace, allow ingress only from pods in tenant-b and pods in tenant-a, egress is in default deny and only egress to kube-dns is allowed"
    ingress:
      - fromEndpoints:
          - {}
      - fromEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: tenant-b
    egress:
      - toEndpoints:
          - {}
      - toEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: 53
                protocol: ANY
            rules:
              dns:
                - matchPattern: "*"
